App.js
Login.js
Main.js
app.json

- (Android) 메인화면 에서 하드웨어에 있는 뒤로가기 버튼 누르면 앱 종료
- (공통) 헤더바 숨김 - 뒤로가기 버튼이 포함되어 있기도 하며, 메인화면에서 불필요.

뒤로가기 버튼 처리

---

src/Login.js
src/Main.js
src/MainShell.js
src/tools/navutils.js

- 백버튼이나 제스처로 메인화면에서 로그인화면으로 진입 방지 작업
- 출결현황 화면 진입 코드 작성

[feature/blocknav] 네비게이션 수정

---

src/MainShell.js
src/Menu.js
src/components/components.js
src/screens/counsel.js
src/tools/apis.js

[feature/counsel] 상담 이력 조회 기능 추가

---

src/tools/dbhelper.js

수강 변경시 발생하는 시간표/출결현황 버그 수정

---

src/config.js

[change localhost]

---

.babelrc
App.js
app.json
babel.config.js
package.json
src/Login.js
src/Main.js
src/MainShell.js
src/Menu.js
src/components/weather.js
src/legal.js
src/screens/about.js
src/screens/attendance.js
src/screens/counsel.js
src/screens/credits.js
src/screens/gradeCert.js
src/screens/meal.js
src/screens/savedCredits.js
src/screens/schedules.js
src/screens/scholarshopHistory.js
src/screens/subjects.js
src/screens/syllabus.js
src/screens/syllabusDetails.js
src/screens/timetable.js
yarn.lock

- 학식 스타일링 부분 개선
- 버전 변경
- 의존성 업데이트
- 업데이트된 의존성에 따른 수정

학식 업데이트 출시 전 추가 수정 작업

---

src/components/weather.js

일단 좌표값은 변경할 필요없었습니다(광명시가 어딘가 했더니 바로옆). 날짜 API의 weather 값의 리턴이 오브젝트에서 배열로 바뀌어서 생긴 문제입니다.

[refactoring] 날짜 api 변경사항 : weather가 오브젝트에서 배열로 변경

---

src/Main.js

카드 위에 *공지사항* 이란 글자가 그대로 남아있어 이것도 주석처리

[hotfix/type]공지사항 카드 위 제목도 주석처리

---

src/Login.js
src/Menu.js

[feature/faster-login]로그인 수행 후 85분간 로그인 없이 메인화면 이동 (#63)

---

src/Login.js
src/components/errorModal.js
src/components/helpModal.js

오류 화면과 도움받기 화면을 개선하여, 오류 발생시 좀 더 자세한 정보 제공은 물론. 오류 정보를 복사하거나 메일 등으로 바로 보고 할 수 있도록 개선.

오류 화면 및 도움받기 화면 개선(#75)

---

src/components/errorModal.js
src/components/helpModal.js
src/components/infoModal.js
src/screens/about.js

InfoModal 레이아웃 수정

---

src/Login.js

[hotfix/timeout] 재로그인 주기 조절

---

src/screens/attendance.js
src/screens/studentTimetable.js

해당 화면 진입 시, 항상 데이터 업데이트 및 DB 저장을 먼저 수행한 후 화면에 표시.
수강변경 등을 하는 경우 결과를 바로 확인할 수 있도록 하기 위함.

[feature/update-before-display] 시간표, 출결 데이터 먼저 갱신 후 표시

---

src/tools/apis.js

앞으로 로컬에서 머지하지 말고 깃허브로만 머지해야겠다.

[hotfix/mistype] 오타수정

---

src/tools/apis.js

getSamFetcher에 인수를 post 인지 확인 볼타입 인수를 추가

[hotfix/counsel] 상담 기록 기능이 작동하지 않는 현상 해결

---

src/MainShell.js
src/Menu.js
src/screens/lectureRoomTimetable.js

강의실별 시간표 조회기능 구현

---

app.json
package.json
src/Main.js
src/MainShell.js
src/Menu.js
src/components/localauth.js
src/components/touchable.js
src/screens/authinfo.js
yarn.lock

PIN 변경 기능은 추후 앱 설정 화면 추가를 통해 추가 예정

인증정보 화면 및 PIN/생체 인증 화면 추가

---

src/Login.js
src/config.js
src/tools/apis.js

변경된 서버의 로그인 API 에 따라 로그인을 효율적인 방식으로 처리하도록 수정 (#126)

[feature/task-split] 로그인 분산 처리

---

src/config.js

skhu-test 도메인으로 다시 이전합니다.
google cloud run의 커스텀 도메인 설정을 성공했습니다.
이 기능은 google cloud run의 인증서 설정을 사용자의 도메인에 맞게 설정해주는 기능을 가지고 있습니다.

[hotfix/gcp-domain] google cloud run 커스텀 도메인 설정

---

src/Login.js
src/components/errorModal.js

- Hooks 형태(함수형) 으로 재작성
- Autofill 지원 추가

Login 컴포넌트 리펙토링

---

src/components/components.js
src/config.js
src/screens/settings.js

PIN 복구, 변경 화면 진입시 강제종료되는 버그 수정 (closes #139)

---

src/Main.js
src/components/whatsNewModal.js
src/config.js
src/screens/about.js
src/screens/settings.js
src/updateInfo.js

- 앱 업데이트 내역 모달 구현
- 앱 설정에 업데이트 내역 모달 설정 추가
- 업데이트 후 한번만 자동으로 나오도록 구현(앱 설정에서 끄면 아예 나오지 않음)

앱 업데이트 내역 모달 구현 (Closes #152)

---

src/legal.js

깜빡하고 빼먹은 프로젝트 참여자 정보 수정. 핫픽스 PR
앱 빌드에는 이미 포함되어 있음.

[hotfix/devinfo] 개발자 정보 수정

---

src/Main.js
src/screens/attendance.js
src/tools/dbhelper.js

출결 정보는 없으나 강의 정보가 있는 경우(예: 비대면 강의. LMS 조회만 가능)
LMS 에서 확인 안내 표시하도록 수정-
코드 스타일 자동수정 포함

다음 강의 정보 표시 오류 수정
